In [100]:
import numpy as np
from numpy.linalg import inv

### Declaring

In [143]:
x = np.array([1,2,3], np.int32)
print(f'Type:{type(x)}')
print(f'Type of elements:{x.dtype}')

Type:<class 'numpy.ndarray'>
Type of elements:int32


In [142]:
print(np.zeros(5, dtype='int16'))
print(np.zeros((2,2), dtype='int16'))

[0 0 0 0 0]
[[0 0]
 [0 0]]


#### NDArrray

In [180]:
x = np.array([[1,2,3,4]])
print(f'X:{x}')
print(f'shape(x):{np.shape(x)}')

x22 = np.ndarray(shape = (2,2), dtype='int', buffer=x)
print(f'x22:{x22}')

x41 = np.ndarray(shape = (4,1), dtype='int', buffer=x)
print(f'x41:{x41}')

x14 = np.ndarray(shape = (1,4), dtype='int', buffer=x)
print(f'x14:{x14}')

X:[[1 2 3 4]]
shape(x):(1, 4)
x22:[[1 2]
 [3 4]]
x41:[[1]
 [2]
 [3]
 [4]]
x14:[[1 2 3 4]]


### Slicing

In [43]:
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x[1,])
print(x[1,2:4])

[5 6 7 8]
[7 8]


### Broadcasting 

Broadcasting takes array inputs and produces array outputs by performing the core function element-wise on the input np

In [14]:
x = np.array([1,2,3,4,5])
print(f'Multipled:{x * 2}')
print(f'Added:{x + 2}')

Multipled:[ 2  4  6  8 10]
Added:[3 4 5 6 7]


#### Add

In [19]:
x = np.array([2,2,2,2,2])
y = np.array([1,2,3,4,5])
np.add(x,y) #x+y

array([3, 4, 5, 6, 7])

#### Multiply

In [169]:
x = np.array([2,2,2,2,2])
y = np.array([1,2,3,4,5])
np.multiply(x,y) #x*y

array([ 2,  4,  6,  8, 10])

#### Operations

In [187]:
x = np.array([4,4,4,4,4])
print(f'sum:{np.sum(x)}')
print(f'max:{np.max(x)}')
print(f'log2:{np.log2(x)}')
x = np.array([100,1000,10000,100000,1000000])
print(f'log10:{np.log10(x)}')

sum:20
max:4
log2:[2. 2. 2. 2. 2.]
log10:[2. 3. 4. 5. 6.]


In [207]:
x = np.array([[1,2],[3,4]])
print(f'x:{x}')
print(f'max axis1:{x.max(0)}')
print(f'max axis2:{x.max(1)}')
print(f'sum axis1:{x.sum(0)}')
print(f'sum axis2:{x.sum(1)}')

x:[[1 2]
 [3 4]]
max axis1:[3 4]
max axis2:[2 4]
sum axis1:[4 6]
sum axis2:[3 7]


In [201]:
x = np.array([[1,2],[3,4],[5,6]])
print(f'shape(x):{np.shape(x)}')
print(f'flatten(x):{x.flatten()}')

shape(x):(3, 2)
flatten(x):[1 2 3 4 5 6]


#### Transpose

In [240]:
A = np.arange(9).reshape(3,3)

print("A:{}".format(A))
print("\nAt:{}".format(np.transpose(A)))


A:[[0 1 2]
 [3 4 5]
 [6 7 8]]

At:[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [213]:
A = np.arange(6).reshape(1,6)
print(np.transpose(A))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


#### Matrix multiplication

In [220]:
A = np.array([1,2,1]).reshape(1,3)
print("A: {}".format(A))
B = np.array([2,2,2]).reshape(3,1)
print("B: {}".format(B))

AB = np.matmul(A,B)
print("\nAB: {}".format(AB))

A: [[1 2 1]]
B: [[2]
 [2]
 [2]]

AB: [[8]]


#### Matrix inverse

In [230]:
A = np.array([3,2,2,2]).reshape(2,2)
print("A: {}".format(A))
print("A-1:{}".format(inv(A)))

A: [[3 2]
 [2 2]]
A-1:[[ 1.  -1. ]
 [-1.   1.5]]


#### Dot product

[Dot product](https://en.wikipedia.org/wiki/Dot_product)

* a1*b1+a2*b2+a3*b3

In [222]:
A = np.array([1,1,1])
B = np.array([1,1,1])
print(np.dot(A,B))

3


#### Max with axis

In [198]:
x = np.array([[1,2],[3,4]])
print(np.max(x))
print(np.max(x, axis=1))
print(np.max(x, axis=0))


x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(np.maximum(x,y))

4
[2 4]
[3 4]
[5 6 7 8]


In [174]:
x = np.eye(5)
print(x)
print(x.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


#### Full like

In [175]:
np.full_like(x, 10, dtype='int16')

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int16)

#### Linspace

[Docs](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [177]:
np.linspace(1.0,10.0,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### Logspace

[Docs](https://numpy.org/doc/stable/reference/generated/numpy.logspace.html)

In [178]:
np.logspace(1.0,10.0,num=10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [210]:
print(np.random.random((3,3)))

[[0.19438903 0.46215365 0.6502499 ]
 [0.67098983 0.14950162 0.55081363]
 [0.26416565 0.64040967 0.00236754]]


#### Filtering/Spacing etc...

In [233]:
x = np.array([1,2,3,4])
print(x[1:2])
print(x[-2])
print(np.any(x>3))
print(np.all(x>3))
print(np.repeat(x,2))
print(np.diag(x))
print(x<=2)

[2]
3
True
False
[1 1 2 2 3 3 4 4]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[ True  True False False]


In [181]:
x = np.array([[1,2],[1,2]])
x[:,1]

array([2, 2])

#### Random initialization

In [182]:
np.random.rand(3,3)

array([[0.77132712, 0.47370336, 0.57822169],
       [0.8052923 , 0.04369623, 0.96336317],
       [0.74995623, 0.72464096, 0.52329688]])

In [183]:
np.random.randint(3,6,size=(3,3))

array([[4, 4, 5],
       [4, 5, 5],
       [4, 4, 4]])

In [184]:
x =np.array([0,45,90], dtype='int16')
np.sin(x)

array([0.        , 0.8509035 , 0.89399666], dtype=float32)

#### Reshape

In [185]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.reshape(1,4))
print(x.reshape(4,1))

[[1 2]
 [3 4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


#### Stacking

In [205]:
x = np.array([1,2])
y = np.array([3,4])
print(np.vstack([x,y]))

x = np.array([1,2])
y = np.array([3,4])
print(np.hstack([x,y]))

[[1 2]
 [3 4]]


[1 2 3 4]


#### Dimensionality

In [208]:
a=np.array([1,2,3])
print(a.ndim)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
print(A.ndim)

1
2
