In [1]:
import numpy as np

In [5]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
a=np.array([3,5,3,4]).reshape(2,2)
a.shape

(2, 2)

In [21]:
a.size

4

In [10]:
np.random.random((3,3))

array([[0.78053799, 0.07235992, 0.95449407],
       [0.69237967, 0.89512404, 0.19315017],
       [0.7366974 , 0.64887893, 0.03324759]])

In [34]:
a = np.array([1,2,3,4]).reshape(2,2)
2*a

array([[2, 4],
       [6, 8]])

In [35]:
a.max()

4

In [36]:
a.min()

1

In [38]:
a.sum()

10

In [24]:
a<3

array([[ True,  True],
       [False, False]])

In [39]:
a.ravel()

array([1, 2, 3, 4])

In [29]:
a=np.array([1,1,1,1]).reshape(2,2)
b=np.array([2,2,2,2]).reshape(2,2)
a*b

array([[2, 2],
       [2, 2]])

In [30]:
a+b

array([[3, 3],
       [3, 3]])

In [31]:
a@b

array([[4, 4],
       [4, 4]])