In [109]:
import numpy as np
from numpy.linalg import inv

In [48]:
A = np.arange(9).reshape(3,3)

In [49]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
At = np.transpose(A)

In [52]:
At

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [47]:
 At[0,2]==A[2,0]

True

In [53]:
A = np.arange(6).reshape(1,6)

In [54]:
A

array([[0, 1, 2, 3, 4, 5]])

In [55]:
At = np.transpose(A)

In [57]:
At

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [101]:
A = np.array([2,2,2,2]).reshape(2,2)
B = np.array([2,2,2,2]).reshape(2,2)
np.matmul(A,B)

array([[8, 8],
       [8, 8]])

In [ ]:
#A must have the same number of columns as B has rows.

In [103]:
A = np.array([1,2,1]).reshape(1,3)
B = np.array([2,2,2]).reshape(3,1)
np.matmul(A,B)

array([[8]])

In [105]:
A = np.array([1,1,1])
B = np.array([1,1,1])
#a1*b1+a2*b2+a3*b3
np.dot(A,B)

3

In [123]:
A = np.array([3,2,2,2]).reshape(2,2)
#A
inv(A)

array([[ 1. , -1. ],
       [-1. ,  1.5]])